/*
 Sliding Menu
 Version: 1.0.5
 (c) 2013 DMXzone.com
 @build 01-07-2013 12:08:27
*/
(function(d){function j(a,c){this.opts=d.extend({},j.options,c);this.$target=d(a);this.init()}var n="iPod"===navigator.platform,o="iPad"===navigator.platform,g="iPhone"===navigator.platform||n||o,f=!!("ontouchstart"in window),m=f?"touchstart":"mousedown",k=f?"touchmove":"mousemove",l=f?"touchend":"mouseup";d.easing["ease-out"]=function(a,c,b,d,e){return d*((c=c/e-1)*c*c+1)+b};j.options={height:"auto",updateTitle:!0,updateBackLabel:!0,mousewheel:!0,ignoreDragOn:["input","select","textarea","button"],
striping:!1};j.prototype={init:function(){this.$menu=this.$target.find(">ul");this.$back=this.$target.parent().find("div.dmxSlidingMenuBack");this.$title=this.$target.parent().find("div.dmxSlidingMenuTitle");this.width=this.$target.width();this.lvl=0;this.defBack=this.$back.find("a").text();this.$back.hide();this.opts.updateTitle&&(this.defTitle=this.$title.text(),this.$title.text(this.$menu.attr("title")||this.defTitle));this.setupLayout();this.setupEventListeners()},setupLayout:function(){var a=
this;this.$target.find("ul").each(function(){d(this).find(">li:has(>a)").each(function(){var a=d(this).prev(),b=d(this).next();0===a.filter(":has(>a)").length&&d(this).addClass("dmxSlidingMenuItemFirst");0===b.filter(":has(>a)").length&&d(this).addClass("dmxSlidingMenuItemLast")});a.opts.striping&&d(this).find(">li:has(>a):odd").addClass("dmxSlidingMenuItemOdd")});this.$menu.css({left:0,top:0}).find("li:has(>ul)>a").addClass("dmxSlidingMenuItemSub");"auto"===this.opts.height?(this.height=this.$target.parent().height(),
this.$target.siblings().each(function(){a.height-=d(this).outerHeight(!0)})):this.height=this.opts.height;this.$target.height(this.height);this.$target.find("ul").css({width:this.width,minHeight:this.height});this.$target.find("ul ul").css({top:0,left:this.width});this.$back.find("a").dmxEllipsis();this.$title.dmxEllipsis()},setupEventListeners:function(){var a=this;d(window).bind("resize.dmxSlidingMenu",function(c){a.onresize.apply(a,arguments)});d(window).bind("orientationchange.dmxSlidingMenu",
function(c){a.onresize.apply(a,arguments)});this.$target.bind(m+".dmxSlidingMenu",function(c){a.handleEvent.apply(a,arguments)});this.$target.bind("click.dmxSlidingMenu",function(c){a.handleEvent.apply(a,arguments)});this.$back.find("a").click(function(c){a.back.apply(a,arguments)});this.opts.mousewheel&&this.$target.bind("mousewheel.dmxSlidingMenu",function(c){a.handleEvent.apply(a,arguments)})},back:function(a){var c=this;a.preventDefault();0>--this.lvl&&(this.lvl=0);0===this.lvl&&this.$back.hide();
this.animate(-this.lvl*this.width);this.opts.updateBackLabel&&0<this.lvl&&(this.$back.find("a").text(this.$target.find("ul:visible").eq(this.lvl-1).attr("title")||this.defBack),setTimeout(function(){c.$back.find("a").dmxEllipsis()},10));this.opts.updateTitle&&(this.$title.text(this.$target.find("ul:visible").eq(this.lvl).attr("title")||this.defTitle),setTimeout(function(){c.$title.dmxEllipsis()},10))},animate:function(a,c,b,d,e){c=c||0;b=null==b?150:b;d=d||(g?"ease":"swing");g?(e&&this.$menu.bind("webkitTransitionEnd",
e),this.$menu.css({"-webkit-transition":"-webkit-transform "+b+"ms "+d,"-webkit-transform":"translate3d("+a+"px, "+c+"px, 0px)"})):this.$menu.stop().animate({left:a+"px",top:c+"px"},b,d,e)},stop:function(){g?this.$menu.css("-webkit-transition","-webkit-transform 0s"):this.$menu.stop()},getPosition:function(){if(g){var a=new WebKitCSSMatrix(this.$menu.css("-webkit-transform"));return{left:a.e,top:a.f}}return this.$menu.position()},handleEvent:function(a){var c=this,b=a.originalEvent.touches,h=function(a){c.handleEvent.apply(c,
arguments)};b&&0<b.length&&(a.pageX=b[0].pageX,a.pageY=b[0].pageY);if(a.type===m){if(-1<d.inArray(a.target.tagName.toLowerCase(),this.opts.ignoreDragOn))return;a.preventDefault();this.target=a.target;this.ondragstart(a);this.$target.bind(k+".dmxSlidingMenu",h);this.$target.bind(l+".dmxSlidingMenu",h);f?this.$target.bind("touchcancelled.dmxSlidingMenu",h):this.$target.bind("mouseleave.dmxSlidingMenu",h)}a.type===k&&(a.preventDefault(),this.ondragmove(a));if(a.type===l||"mouseleave"===a.type||"touchcancelled"===
a.type)this.$target.unbind(k+".dmxSlidingMenu"),this.$target.unbind(l+".dmxSlidingMenu"),f?this.$target.unbind("touchcancelled.dmxSlidingMenu"):this.$target.unbind("mouseleave.dmxSlidingMenu"),this.ondragend(a),f&&!this.dragging&&(b=a.originalEvent.changedTouches[0],h=document.createEvent("MouseEvents"),h.initEvent("click",!0,!0,a.view,1,b.screenX,b.screenY,b.clientX,b.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null),a.target.dispatchEvent(h));this["on"+a.type]&&this["on"+a.type].apply(this,
arguments)},ondragstart:function(a){this.dragging=!1;this.speed=0;this.pos=a.pageY;this.time=a.timeStamp;this.stop()},ondragmove:function(a){var c=a.pageY-this.pos;if(5<Math.abs(c)||this.dragging){a.stopPropagation();this.dragging=!0;var b=this.getPosition();if(0<b.top+c||b.top+c<-(this.$target.find("ul:visible").eq(this.lvl).outerHeight()-this.$target.height()))c/=2;this.animate(b.left,b.top+c,0);0<this.speed?(this.speed+=1E3*(c/(a.timeStamp-this.time)),this.speed/=2):this.speed=1E3*(c/(a.timeStamp-
this.time));this.pos=a.pageY;this.time=a.timeStamp}},ondragend:function(){var a=this,c=Math.min(Math.max(this.speed,-1E3),1E3),b=c*c/8/1E3,d=-(Math.abs(c)/1E3)/-1.5,e=this.getPosition();this.animate(e.left,0>c?e.top-b:e.top+b,1E3*d,"ease-out",function(){var b=a.getPosition();g&&a.$menu.unbind("webkitTransitionEnd");0<b.top&&a.animate(b.left,0);var c=a.$target.find("ul:visible").eq(a.lvl).outerHeight()-a.$target.height();b.top<-c&&a.animate(b.left,-c)})},onclick:function(a){var c=this,b=d(a.target).closest("a");
this.dragging&&a.preventDefault();!this.dragging&&b.hasClass("dmxSlidingMenuItemSub")&&(a.preventDefault(),b.closest("ul").find("ul").hide(),b.closest("li").find(">ul").show(),this.lvl=b.parents("ul").length,this.animate(-this.lvl*this.width),this.opts.updateBackLabel&&(this.$back.find("a").text(b.closest("ul").attr("title")||this.defBack),setTimeout(function(){c.$back.find("a").dmxEllipsis()},10)),this.opts.updateTitle&&(this.$title.text(b.closest("li").find(">ul").attr("title")||this.defTitle),
setTimeout(function(){c.$title.dmxEllipsis()},10)),this.$back.show())},onresize:function(){this.width=this.$target.width();this.setupLayout();this.animate(-this.lvl*this.width)},onmousewheel:function(a,c){a.preventDefault();a.stopPropagation();var b=parseInt(this.$menu.css("top"))+c*this.$menu.find("li").outerHeight(!0),b=Math.min(Math.max(b,this.$target.height()-this.$target.find("ul:visible").eq(this.lvl).outerHeight()),0),d=this.getPosition();this.animate(d.left,b)}};d.fn.dmxSlidingMenu=function(a){var c=
Array.prototype.slice.call(arguments,1);this.each(function(){var b;d(this).data("SlidingMenu")?b=d(this).data("SlidingMenu"):(b=new j(this,a),d(this).data("SlidingMenu",b));"string"===typeof a&&b[a]&&b[a].apply(b,c)});return this};d.fn.dmxEllipsis=function(a){var c=document.documentElement.style;return"textOverflow"in c||"OTextOverflow"in c?this:this.each(function(){var b=d(this);if("hidden"==b.css("overflow")){var c=b.html();b.width();var e=d(this.cloneNode(!0)).hide().css({position:"absolute",width:"auto",
overflow:"visible","max-width":"inherit"});b.after(e);for(var i=c,f=i.length;0<f&&e.width()>b.width();){for(i=i.substr(0,--f);" "==i.charAt(f-1);)i=i.substr(0,--f);e.html(i+"&hellip;")}b.html(e.html());e.remove();if(!0==a){var g=b.width();setInterval(function(){b.width()!=g&&(g=b.width(),b.html(c),b.ellipsis())},200)}}})}})(jQuery);
